#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Autogenerated by Model Generator (0.2)
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

from app_db_model import *


class AppDBConstants(object):

    PERSON_SEX_FEMALE = Person.SEX_FEMALE
    PERSON_SEX_MALE = Person.SEX_MALE
    PERSON_SEX_UNKNOWN = Person.SEX_UNKNOWN
    PERSON_ALL_SEX_CANDIDATES = Person.ALL_SEX_CANDIDATES