#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Autogenerated by Model Generator (0.2)
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

from calypso.co_sql import Field, ModelIface, Table, FieldTypeEnum
from calypso.co_executor import g_co_executor

class OrdersModel(ModelIface):
    TABLE_NAME = 'orders'
    # DB_NAME = 'go'
    def __init__(self, id=None, serial=None, person_id=None, create_time=None):
        super(OrdersModel, self).__init__()
        self.id = Field(name='id', type=int, value=id, default=None, restriction=None)
        self.serial = Field(name='serial', type=str, value=serial, default='', restriction=None)
        self.person_id = Field(name='person_id', type=int, value=person_id, default=0, restriction=None)
        self.create_time = Field(name='create_time', type=str, value=create_time, default='0000-00-00 00:00:00', restriction=None)

class Orders(Table):
    def __init__(self):
        super(Orders, self).__init__(OrdersModel, executor=g_co_executor)

class PersonModel(ModelIface):
    TABLE_NAME = 'person'
    # DB_NAME = 'go'
    SEX_FEMALE = FieldTypeEnum('FEMALE')
    SEX_MALE = FieldTypeEnum('MALE')
    SEX_UNKNOWN = FieldTypeEnum('UNKNOWN')
    ALL_SEX_CANDIDATES = (
        SEX_FEMALE
        ,SEX_MALE
        ,SEX_UNKNOWN )
    def __init__(self, id=None, name=None, sex=SEX_UNKNOWN, age=None):
        super(PersonModel, self).__init__()
        self.id = Field(name='id', type=int, value=id, default=None, restriction=None)
        self.name = Field(name='name', type=str, value=name, default='', restriction=None)
        self.sex = Field(name='sex', type=FieldTypeEnum, value=sex, default=self.SEX_UNKNOWN, restriction=self.ALL_SEX_CANDIDATES)
        self.age = Field(name='age', type=int, value=age, default=0, restriction=None)

class Person(Table):
    SEX_FEMALE = FieldTypeEnum('FEMALE')
    SEX_MALE = FieldTypeEnum('MALE')
    SEX_UNKNOWN = FieldTypeEnum('UNKNOWN')
    ALL_SEX_CANDIDATES = (
        SEX_FEMALE
        ,SEX_MALE
        ,SEX_UNKNOWN )
    def __init__(self):
        super(Person, self).__init__(PersonModel, executor=g_co_executor)

