#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Fri May  8 15:09:42 2015
# ht <515563130@qq.com, weixin:jacoolee>

"""
Automatically generated by script.
"""

# from calypso.co_sql import * # * for test
from calypso.co_sql import Field, ModelIface, Table, FieldTypeEnum

# maybe in init file
from calypso.co_executor import g_co_executor


class Person_Model(ModelIface):
    TABLE_NAME = 'person'      # must have
    def __init__(self):
        super(Person_Model, self).__init__()
        self.id = Field(name='id', type=int, default=0)
        self.name = Field(name='name', type=str, default='')
        self.sex = Field(name='sex', type=FieldTypeEnum, default='MALE')
        self.age = Field(name='age', type=str, default='')


class Person(Table):
    def __init__(self):
        super(Person, self).__init__(Person_Model, executor=g_co_executor)


class Orders_Model(ModelIface):
    TABLE_NAME = 'orders'      # must have
    def __init__(self):
        super(Orders_Model, self).__init__()
        self.id = Field(name='id', type=int, default=0)
        self.serial = Field(name='serial', type=str, default='')
        self.person_id = Field(name='person_id', type=str, default='')
        self.create_time = Field(name='create_time', type=str, default='')


class Orders(Table):
    def __init__(self):
        super(Orders, self).__init__(Orders_Model, executor=g_co_executor)
